parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/data/blog.sqlite'

doctrine:
    dbal:
        # driver: 'pdo_sqlite'
        # server_version: '3.20'
        # charset: utf8mb4

        # url: '%env(resolve:DATABASE_URL)%'

        # default_connection:     default
        default_connection:     db_yii
        # default_connection:     db_symfony
        # default_connection:     db_cake
        connections:
            default:
                driver:         'pdo_sqlite'
                server_version: '3.20'
                # dbname:         system
                charset:        utf8
                # url:            sqlite:///%kernel.project_dir%/var/data.sqlite
                url:            '%env(resolve:DATABASE_URL)%'
                # url:            '%env(DATABASE_URL)%'

            db_yii:
                driver:         'pdo_sqlite'
                server_version: '3.20'
                # dbname:         db_yii
                charset:        utf8
                url:            sqlite:///%kernel.project_dir%/var/data/blog_yii.sqlite

            db_cake:
                driver:         'pdo_sqlite'
                server_version: '3.20'
                # dbname:         db_cake
                charset:        utf8
                url:            sqlite:///%kernel.project_dir%/var/data/blog_cake.sqlite

            db_symfony:
                driver:         'pdo_sqlite'
                server_version: '3.20'
                # dbname:         db_symfony
                charset:        utf8
                url:            sqlite:///%kernel.project_dir%/var/data/blog_symfony.sqlite

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        # default_entity_manager: orm_symfony
        # entity_managers:
        #     default:
        #         connection: default
        #         # auto_mapping: true
        #         # mappings:
        #         #     Main:
        #         #         is_bundle: false
        #         #         type: annotation
        #         #         dir: '%kernel.project_dir%/src/Entity/Main'
        #         #         prefix: 'App\Entity\Main'
        #         #         alias: Main

        #     orm_yii:
        #         connection: db_yii
        #         # mappings:
        #         #     Customer:
        #         #         is_bundle: false
        #         #         type: annotation
        #         #         dir: '%kernel.project_dir%/src/Entity/Customer'
        #         #         prefix: 'App\Entity\Customer'
        #         #         alias: Customer
        #     orm_cake:
        #         connection: db_cake

        #     orm_symfony:
        #         connection: db_symfony
        #         mappings:
        #             Comment:
        #                 is_bundle: false
        #                 type: annotation
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity\Comment'
        #                 alias: Comment
        #             Post:
        #                 is_bundle: false
        #                 type: annotation
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity\Post'
        #                 alias: Post
        #             Tag:
        #                 is_bundle: false
        #                 type: annotation
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity\Tag'
        #                 alias: Tag
        #             User:
        #                 is_bundle: false
        #                 type: annotation
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity\User'
        #                 alias: User